# Generated by Django 4.2 on 2023-04-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_db',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.CharField(blank=True, max_length=10)),
                ('purchaser', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField()),
                ('is_astar', models.BooleanField(default=False)),
                ('aster_status', models.BooleanField(default=False)),
                ('is_piku', models.BooleanField(default=False)),
                ('piku_status', models.BooleanField(default=False)),
                ('cost', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Customer.customers')),
            ],
        ),
    ]
