# Generated by Django 4.2 on 2023-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0003_remove_worker_db_workdone'),
        ('Owner', '0003_work_is_complited'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='workDone',
            field=models.ManyToManyField(blank=True, related_name='workDone', to='Worker.worker_db'),
        ),
        migrations.AddField(
            model_name='work',
            name='worker',
            field=models.ManyToManyField(blank=True, to='Worker.worker_db'),
        ),
    ]
