# Generated by Django 4.2.1 on 2023-05-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_alter_work_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_db',
            name='user',
        ),
        migrations.AddField(
            model_name='owner_db',
            name='mobileNo',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
