# Generated by Django 4.2.1 on 2023-05-05 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Owner', '0008_alter_owner_db_mobileno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner_db',
            name='mobileNo',
        ),
        migrations.AddField(
            model_name='owner_db',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
