# Generated by Django 4.2.1 on 2023-05-05 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Owner', '0009_remove_owner_db_mobileno_owner_db_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_db',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
