# Generated by Django 4.2.1 on 2023-05-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0012_remove_work_aster_status_remove_work_piku_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='is_astar',
            new_name='astar',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='is_piku',
            new_name='piku',
        ),
    ]
