# Generated by Django 4.2.1 on 2023-05-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0013_rename_is_astar_work_astar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='astar',
            field=models.CharField(choices=[('No Need', 'No Need'), ('Need', 'Need'), ('Fulfilled', 'Fulfilled'), ('Provided', 'Provided')], default='No Need', max_length=30),
        ),
        migrations.AlterField(
            model_name='work',
            name='piku',
            field=models.CharField(choices=[('No Need', 'No Need'), ('Need', 'Need'), ('Fulfilled', 'Fulfilled')], default='No Need', max_length=30),
        ),
    ]
