# Generated by Django 4.2.1 on 2023-05-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0014_alter_work_astar_alter_work_piku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='billno',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
