# Generated by Django 4.2.1 on 2023-05-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0020_remove_work_workdone_remove_work_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner_db',
        ),
    ]
