# Generated by Django 4.2.1 on 2023-05-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0021_delete_owner_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(default=1, limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.CASCADE, to='Owner.member'),
            preserve_default=False,
        ),
    ]
