# Generated by Django 4.2.1 on 2023-05-21 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0022_work_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'is_owner': False}, on_delete=django.db.models.deletion.CASCADE, to='Owner.member'),
        ),
    ]
