# Generated by Django 4.2.1 on 2023-05-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0025_work_bill_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.organization')),
            ],
        ),
    ]
