# Generated by Django 4.2.1 on 2023-05-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0026_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Owner.types'),
            preserve_default=False,
        ),
    ]
