# Generated by Django 4.2.1 on 2023-05-05 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_remove_customers_measurement_measurement_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='user',
        ),
        migrations.AddField(
            model_name='customers',
            name='mobileno',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1111111111)]),
        ),
    ]
