# Generated by Django 4.2.1 on 2023-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_remove_customers_user_customers_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.CharField(default='nothing', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
