# Generated by Django 4.2.1 on 2023-05-21 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0019_alter_work_organization'),
        ('Customer', '0004_customers_address_alter_customers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Owner.organization'),
            preserve_default=False,
        ),
    ]
