# Generated by Django 4.2.1 on 2023-05-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0019_alter_work_organization'),
        ('Customer', '0006_alter_customers_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.organization'),
        ),
    ]
