# Generated by Django 4.2 on 2023-04-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Owner', '0003_work_is_complited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ManyToManyField(blank=True, related_name='work', to='Owner.work')),
                ('workDone', models.ManyToManyField(blank=True, related_name='workDone', to='Owner.work')),
            ],
        ),
    ]
