# Generated by Django 4.2 on 2023-04-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_db',
            name='work',
        ),
    ]
