# Generated by Django 4.2 on 2023-04-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker', '0002_remove_worker_db_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker_db',
            name='workDone',
        ),
    ]
