# Generated by Django 4.2.1 on 2023-05-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0020_remove_work_workdone_remove_work_worker'),
        ('Worker', '0003_remove_worker_db_workdone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker_db',
        ),
    ]
